name: geohash
description: A simple geohashing library for dart
version: 0.2.1
author: Adam Stark <llamadonica@gmail.com>
homepage: https://github.com/llamadonica/dart-geohash

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.2.0