name: geo_hash_xy
version: 0.2.3
description: A simple geohashing library for dart forked from DISCONTINUED geohash [https://pub.dev/packages/geohash]
homepage: https://github.com/BMEC/dart-geo_hash_xy
repository: https://github.com/BMEC/dart-geo_hash_xy
issue_tracker: https://github.com/BMEC/dart-geo_hash_xy/issues
environment:
  sdk: '>=2.0.1 <3.0.0'

dependencies:
  meta: ^1.2.4

dev_dependencies:
  test: ^1.2.0